### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by kaviars** [kaaposc/latvia-eid-middleware#1]
Error:
```
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
==> ERROR: Failure while downloading https://www.pmlp.gov.lv/sites/pmlp/files/media_file/latvia-eid_2.0.13-1_ubuntu_0.zip
```
Attempt to find solution: https://forum.manjaro.org/t/failed-to-build-latvia-eid-middleware-package/112042

**Comment by kaaposc** [comment]
It seems `curl` for some reason doesn't like the `pmlp.gov.lv` site:
```
$ curl https://www.pmlp.gov.lv/sites/pmlp/files/media_file/latvia-eid_2.0.13-1_ubuntu_0.zip
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
$ curl https://www.pmlp.gov.lv/lv/datora-sagatavosana-darbam-ar-eid
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```
The second URL is the site where the downloadable libraries are posted. One solution is to grab the needed file using either `wget` or just your browser, move the zip file into the build directory of the package and rename it `latvia-eid-middleware-2.0.13-1.zip` ("$pkgname-$pkgver-$pkgrel" pattern). The `makepkg` should then see the file, check its sha512 and move on with the build process.

**Comment by kaaposc** [comment]
Solution 2 would be [using `aria2` for pacman xfers](https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#aria2) because `aria2` also has no problems getting the file.

**Comment by pagaidu** [comment]
Thank you! Got it working.

**Comment by kaviars** [comment]
Thank you! Got it working!

**Comment by kaaposc** [comment]
The real problem was pmlp web server filtering requests by user-agent header, so the package was modified to send "Mozilla" user agent when trying to download the source file.
